// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZWzmNjozN3y1n9CiQZ4kakKy1UPDhzco',
    appId: '1:156852939589:web:26acb87c0dce59e4552c2c',
    messagingSenderId: '156852939589',
    projectId: 'bass-training-app-360af',
    authDomain: 'bass-training-app-360af.firebaseapp.com',
    storageBucket: 'bass-training-app-360af.firebasestorage.app',
    measurementId: 'G-0F7JCF0JES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrbCrjw9vCTvB5SedqGflJnPrqu5Ik72A',
    appId: '1:156852939589:android:51568c0951f001d9552c2c',
    messagingSenderId: '156852939589',
    projectId: 'bass-training-app-360af',
    storageBucket: 'bass-training-app-360af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcOeyQuK8S1A9KyAzjEjRY8MFpGQKqHWk',
    appId: '1:156852939589:ios:b96bc0d80ee070bd552c2c',
    messagingSenderId: '156852939589',
    projectId: 'bass-training-app-360af',
    storageBucket: 'bass-training-app-360af.firebasestorage.app',
    iosBundleId: 'com.example.bassTrainingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcOeyQuK8S1A9KyAzjEjRY8MFpGQKqHWk',
    appId: '1:156852939589:ios:b96bc0d80ee070bd552c2c',
    messagingSenderId: '156852939589',
    projectId: 'bass-training-app-360af',
    storageBucket: 'bass-training-app-360af.firebasestorage.app',
    iosBundleId: 'com.example.bassTrainingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZWzmNjozN3y1n9CiQZ4kakKy1UPDhzco',
    appId: '1:156852939589:web:99700a299b26b2ff552c2c',
    messagingSenderId: '156852939589',
    projectId: 'bass-training-app-360af',
    authDomain: 'bass-training-app-360af.firebaseapp.com',
    storageBucket: 'bass-training-app-360af.firebasestorage.app',
    measurementId: 'G-073ED8T1ZC',
  );
}
