// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaYmzc1Yv6PzicJvCvsVXhDdLl7QRlt1Q',
    appId: '1:208799525750:web:992e22fb8417482e072857',
    messagingSenderId: '208799525750',
    projectId: 'bass-training-app-88bb9',
    authDomain: 'bass-training-app-88bb9.firebaseapp.com',
    storageBucket: 'bass-training-app-88bb9.firebasestorage.app',
    measurementId: 'G-0F4TCQSPX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjFYupl1qI-kpJEOp7HPNuIC2QS9LnC8Q',
    appId: '1:208799525750:android:f26877d9d076dffe072857',
    messagingSenderId: '208799525750',
    projectId: 'bass-training-app-88bb9',
    storageBucket: 'bass-training-app-88bb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYp2d1aJdfQ-nFWFwCinn_QQOj6BalyiI',
    appId: '1:208799525750:ios:13d161e7768c1930072857',
    messagingSenderId: '208799525750',
    projectId: 'bass-training-app-88bb9',
    storageBucket: 'bass-training-app-88bb9.firebasestorage.app',
    iosBundleId: 'com.basstraining.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYp2d1aJdfQ-nFWFwCinn_QQOj6BalyiI',
    appId: '1:208799525750:ios:13d161e7768c1930072857',
    messagingSenderId: '208799525750',
    projectId: 'bass-training-app-88bb9',
    storageBucket: 'bass-training-app-88bb9.firebasestorage.app',
    iosBundleId: 'com.basstraining.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaYmzc1Yv6PzicJvCvsVXhDdLl7QRlt1Q',
    appId: '1:208799525750:web:4fa056b8886161d2072857',
    messagingSenderId: '208799525750',
    projectId: 'bass-training-app-88bb9',
    authDomain: 'bass-training-app-88bb9.firebaseapp.com',
    storageBucket: 'bass-training-app-88bb9.firebasestorage.app',
    measurementId: 'G-GDSMJJZQ1H',
  );
}
